import React from 'react';
import Head from 'next/head';
import '../styles/globals.scss';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import { store } from '../redux/core/store';
import { Provider } from 'react-redux';
config.autoAddCss = false;

import Header from '../components/header';
import Footer from '../components/footer';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Provider store={store}>
        <Head>
          <title> Okiro </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>{' '}
        <div className="global__content">
          <Header />
          <Component {...pageProps} />
          <Footer />
        </div>{' '}
      </Provider>
    </>
  );
}

export default MyApp;
