import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import { config } from '@fortawesome/fontawesome-svg-core';
import { store } from '../redux/core/store';
import { Provider } from 'react-redux';
import { useRouter } from 'next/router';
import '../styles/globals.scss';
import '@fortawesome/fontawesome-svg-core/styles.css';

import NonAuthLayout from '../layout/nonAuthLauout';
config.autoAddCss = false;

function MyApp({ Component, pageProps }) {
  const router = useRouter();
  const [layout, setLayout] = useState(true);

  useEffect(() => {
    router.pathname === '/sign-in' ? setLayout(false) : setLayout(true);
  }, [router.pathname]);
  return (
    <>
      <Provider store={store}>
        <Head>
          <title> Okiro </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>{' '}
        {layout ? (
          <NonAuthLayout>
            <Component {...pageProps} />
          </NonAuthLayout>
        ) : (
          <Component {...pageProps} />
        )}
      </Provider>
    </>
  );
}

export default MyApp;
